In [2]:
# Import needed packages
# You may add or remove packages should you need them
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.datasets import load_iris
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import KFold, LeaveOneOut, cross_val_score

# Set random seed
np.random.seed(0)

# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
# Set Seaborn aesthetic parameters to defaults
sns.set()

In [4]:
# Load the Iris dataset included with scikit-learn

iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
# Put data in a pandas DataFrame

df_iris = pd.DataFrame(iris.data, columns=iris.feature_names)
df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
# Add target and class to DataFrame

df_iris["target"] = iris.target

df_iris["class"] = iris.target_names[iris.target]

In [10]:
# Show 10 random samples

df_iris.sample(n=10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
92                 5.8               2.6                4.0               1.2   
141                6.9               3.1                5.1               2.3   
130                7.4               2.8                6.1               1.9   
119                6.0               2.2                5.0               1.5   
48                 5.3               3.7                1.5               0.2   
143                6.8               3.2                5.9               2.3   
122                7.7               2.8                6.7               2.0   
63                 6.1               2.9                4.7               1.4   
26                 5.0               3.4                1.6               0.4   
64                 5.6               2.9                3.6               1.3   

     target       class  
92        1  versicolor  
141       2   virginica  
130       2   virginica  
119       2   virginica  
48        0      setosa  
143       2   virginica  
122       2   virginica  
63        1  versicolor  
26        0      setosa  
64        1  versicolor

In [15]:
df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target      class  
0         0     setosa  
1         0     setosa  
2         0     setosa  
3         0     setosa  
4         0     setosa  
..      ...        ...  
145       2  virginica  
146       2  virginica  
147       2  virginica  
148       2  virginica  
149       2  virginica  

[150 rows x 6 columns]

In [11]:
# now... implement the LDA (bear in mind that you do pass it the y's and it is supervised!)

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()


In [13]:
# same process as always, identify your X's and your y's

x = df_iris.iloc[:,0:-2]
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [14]:
y = df_iris.iloc[:,-2]
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [16]:
#train-test-split

X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y, test_size=0.3, random_state=0)

In [19]:
# Scale the X's

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
# apply the lda transformation

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis()

X_train_lda = lda.fit(X_train_scaled,y_train).transform(X_train_scaled)
X_test_lda = lda.transform(X_test_scaled)

In [21]:
# select 2 principal components

X_train_lda

array([[-0.93534728,  2.56340654],
       [-4.9854655 ,  0.12984179],
       [-6.71818728, -2.28054655],
       [-4.50416279,  2.1562057 ],
       [-6.05586017,  1.42531684],
       [-0.85339282,  1.58864502],
       [-6.24525673, -0.85251282],
       [-2.35585784, -0.7209366 ],
       [-0.84540183,  1.70265893],
       [-4.07198666,  0.13954656],
       [-3.67867911,  0.99586764],
       [-4.85461429,  0.63957594],
       [-4.815563  ,  0.36717819],
       [-1.03351774, -0.06914412],
       [-4.74968477, -0.75150098],
       [-2.12692883, -1.0841014 ],
       [ 6.96274732,  0.6311119 ],
       [-5.49216896,  0.15037761],
       [-1.90661334,  0.93348185],
       [-0.15965983, -0.10313754],
       [-1.76011418,  1.14487246],
       [-2.18415219,  0.38057744],
       [-5.10785032,  0.13432765],
       [ 8.5552578 , -0.77296709],
       [ 7.72225853,  0.67356318],
       [-5.21505839,  0.26102083],
       [-1.17102799,  0.59183631],
       [ 7.83631832,  0.02869204],
       [ 9.35553499,

In [22]:
# take a look at the new axes for the data and plot them

lda.scalings_

array([[ 1.13900041, -0.14519003],
       [ 0.5028995 , -0.88998308],
       [-4.54370903,  1.8899462 ],
       [-2.03103272, -2.19576071]])

In [23]:
# what about the variability?

lda.explained_variance_ratio_

array([0.99231557, 0.00768443])

In [24]:
# Run a Random Forest Classifier with the transformed data


from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
forest_lda = RandomForestClassifier()
forest_lda.fit(X_train_lda, y_train)
y_pred_lda = forest_lda.predict(X_test_lda)
metrics.accuracy_score(y_test, y_pred_lda)

0.9777777777777777

In [25]:
#Check the new acuracy! Is it higher or lower than what you obtain selecting 2 features and applying a Random Forest Directly?


forest = RandomForestClassifier()
forest.fit(X_train_scaled[:,:2], y_train)
y_pred = forest_lda.predict(X_test_scaled[:,:2])
metrics.accuracy_score(y_test, y_pred)

0.4